// ========================================
// AI TALENT INTELLIGENCE PLATFORM - MOCK DATA
// ========================================

import type {
  CandidateProfile,
  JobPosition,
  SourcingStrategy,
  OutreachCampaign,
  MarketIntelligence,
  CompanyProfile,
  TalentPool,
  SemanticSearchQuery,
  RecruitmentAnalytics,
} from './recruitment-types'

// ==========================================
// CANDIDATE PROFILES
// ==========================================
export const candidateProfiles: CandidateProfile[] = [
  {
    id: 'cand-001',
    name: 'Bruno Costa',
    email: 'bruno.costa@email.com',
    phone: '+351 934 567 890',
    currentRole: 'CFO',
    currentCompany: 'Startup ABC',
    location: 'Lisboa, Portugal',
    yearsExperience: 15,
    skills: [
      { name: 'Financial Planning', level: 'expert', yearsExperience: 15, verified: true, endorsements: 45 },
      { name: 'M&A', level: 'expert', yearsExperience: 10, verified: true, endorsements: 32 },
      { name: 'IPO', level: 'advanced', yearsExperience: 5, verified: true, endorsements: 18 },
      { name: 'Strategy', level: 'expert', yearsExperience: 12, verified: true, endorsements: 28 },
      { name: 'Team Leadership', level: 'expert', yearsExperience: 10, verified: false },
      { name: 'Investor Relations', level: 'advanced', yearsExperience: 8, verified: true },
    ],
    experience: [
      {
        id: 'exp-001',
        company: 'Startup ABC',
        role: 'CFO',
        startDate: new Date('2021-03-01'),
        isCurrent: true,
        description: 'Liderança financeira completa de startup tecnológica em fase de crescimento acelerado.',
        achievements: [
          'Liderou Series B de €25M',
          'Implementou processos de reporting para investidores',
          'Preparação para IPO iniciada em 2024',
          'Reduziu custos operacionais em 22%',
        ],
        companyType: 'startup',
        companySize: '50-100',
        industry: 'Technology',
        location: 'Lisboa, Portugal',
      },
      {
        id: 'exp-002',
        company: 'Tech Corp International',
        role: 'VP Finance',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2021-02-28'),
        isCurrent: false,
        description: 'Gestão financeira para região EMEA de multinacional tecnológica.',
        achievements: [
          'Participou em 2 processos de M&A',
          'Gestão de budget de €150M',
          'Implementou SAP S/4HANA',
        ],
        companyType: 'corporate',
        companySize: '1000+',
        industry: 'Technology',
        location: 'Lisboa, Portugal',
      },
      {
        id: 'exp-003',
        company: 'Big Four Consulting',
        role: 'Senior Manager',
        startDate: new Date('2012-01-01'),
        endDate: new Date('2017-05-31'),
        isCurrent: false,
        description: 'Consultoria financeira e M&A para clientes corporate.',
        achievements: [
          'Liderou +20 projetos de due diligence',
          'Promoção a Senior Manager em 3 anos',
        ],
        companyType: 'corporate',
        companySize: '1000+',
        industry: 'Consulting',
        location: 'Lisboa, Portugal',
      },
    ],
    education: [
      {
        id: 'edu-001',
        institution: 'Nova SBE',
        degree: 'MBA',
        field: 'Finance',
        startDate: new Date('2010-09-01'),
        endDate: new Date('2012-06-30'),
        grade: 'Distinction',
      },
      {
        id: 'edu-002',
        institution: 'Universidade de Lisboa',
        degree: 'Licenciatura',
        field: 'Economia',
        startDate: new Date('2005-09-01'),
        endDate: new Date('2009-06-30'),
        grade: '17/20',
      },
    ],
    languages: [
      { name: 'Português', level: 'native' },
      { name: 'Inglês', level: 'fluent' },
      { name: 'Espanhol', level: 'professional' },
    ],
    linkedinUrl: 'https://linkedin.com/in/brunocosta',
    cvUrl: '/cvs/bruno-costa.pdf',
    source: 'executive_search',
    status: 'in_process',
    aiScore: 95,
    aiAnalysis: {
      id: 'analysis-001',
      candidateId: 'cand-001',
      generatedAt: new Date('2025-05-22'),
      summary: 'Executivo financeiro sénior com forte background em startups tecnológicas e experiência comprovada em IPO. Perfil ideal para posições de CFO em empresas em fase de crescimento acelerado ou preparação para mercados de capitais.',
      seniorityLevel: 'c-level',
      specializations: ['IPO Preparation', 'M&A', 'Startup Finance', 'Investor Relations'],
      strengths: [
        {
          category: 'Experiência IPO',
          description: 'Experiência direta na preparação de empresa para IPO',
          evidence: ['Processo IPO em curso na Startup ABC', 'Conhecimento de compliance e reporting'],
          confidence: 92,
        },
        {
          category: 'Background Diversificado',
          description: 'Combinação única de experiência em startup, corporate e consultoria',
          evidence: ['Big Four', 'Multinacional', 'Startup em crescimento'],
          confidence: 95,
        },
        {
          category: 'Track Record M&A',
          description: 'Vasta experiência em processos de M&A e due diligence',
          evidence: ['+20 projetos de DD', '2 processos M&A na Tech Corp'],
          confidence: 90,
        },
      ],
      gaps: [
        {
          category: 'Experiência Internacional',
          description: 'Carreira maioritariamente focada em Portugal',
          evidence: ['Todas as posições em Lisboa'],
          confidence: 75,
        },
      ],
      riskSignals: [],
      culturalFitIndicators: [
        { dimension: 'Entrepreneurial Mindset', score: 92, indicators: ['Experiência startup', 'Adaptabilidade'] },
        { dimension: 'Leadership', score: 88, indicators: ['Gestão de equipas', 'Crescimento de pessoas'] },
        { dimension: 'Strategic Thinking', score: 94, indicators: ['Visão de longo prazo', 'IPO prep'] },
      ],
      careerTrajectory: 'ascending',
      marketValue: 'premium',
      recommendations: [
        'Forte candidato para posições de CFO em scale-ups',
        'Ideal para empresas em preparação para IPO ou Series C+',
        'Considerar para posições de board advisor',
      ],
      similarProfiles: ['cand-005', 'cand-012'],
      matchScores: [
        { jobId: 'job-003', jobTitle: 'CFO - Chief Financial Officer', score: 95, matchedCriteria: ['IPO experience', 'M&A', 'Startup background'], missingCriteria: [] },
      ],
    },
    scorecards: [
      {
        id: 'sc-001',
        candidateId: 'cand-001',
        jobId: 'job-003',
        evaluatorId: 'user-001',
        evaluatorName: 'Maria Santos',
        createdAt: new Date('2025-05-20'),
        overallScore: 4.5,
        criteria: [
          { name: 'Technical Skills', score: 5, weight: 30, notes: 'Excelente background técnico' },
          { name: 'Leadership', score: 4, weight: 25, notes: 'Forte presença executiva' },
          { name: 'Cultural Fit', score: 5, weight: 20, notes: 'Alinhado com valores' },
          { name: 'Experience Relevance', score: 5, weight: 25, notes: 'IPO experience crucial' },
        ],
        recommendation: 'strong_hire',
        notes: 'Candidato excepcional para a posição de CFO. Experiência IPO é diferenciadora.',
        isAIGenerated: false,
      },
    ],
    notes: [
      {
        id: 'note-001',
        authorId: 'user-001',
        authorName: 'Maria Santos',
        content: 'Primeira chamada muito positiva. Bruno demonstrou forte interesse na oportunidade e alinhamento com a cultura. Disponibilidade para começar em 60 dias.',
        createdAt: new Date('2025-05-18'),
        visibleTo: 'team',
        mentions: [],
      },
    ],
    interactions: [
      {
        id: 'int-001',
        candidateId: 'cand-001',
        type: 'linkedin',
        direction: 'outbound',
        subject: 'Oportunidade CFO',
        content: 'InMail inicial de abordagem',
        outcome: 'positive',
        nextAction: 'Agendar chamada',
        performedBy: 'Maria Santos',
        performedAt: new Date('2025-05-15'),
      },
      {
        id: 'int-002',
        candidateId: 'cand-001',
        type: 'call',
        direction: 'outbound',
        subject: 'Screening Call',
        content: 'Chamada de 45min para apresentação da oportunidade e validação de interesse',
        outcome: 'positive',
        nextAction: 'Enviar job description detalhada',
        performedBy: 'Maria Santos',
        performedAt: new Date('2025-05-18'),
      },
    ],
    tags: ['C-Level', 'IPO', 'Startup', 'Finance', 'High Priority'],
    starred: true,
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2025-05-22'),
  },
  {
    id: 'cand-002',
    name: 'Ricardo Neves',
    email: 'ricardo.neves@email.com',
    phone: '+351 912 345 678',
    currentRole: 'Senior Software Engineer',
    currentCompany: 'Tech Company XYZ',
    location: 'Lisboa, Portugal',
    yearsExperience: 8,
    skills: [
      { name: 'React', level: 'expert', yearsExperience: 6, verified: true, endorsements: 78 },
      { name: 'Node.js', level: 'expert', yearsExperience: 7, verified: true, endorsements: 65 },
      { name: 'TypeScript', level: 'expert', yearsExperience: 5, verified: true, endorsements: 52 },
      { name: 'AWS', level: 'advanced', yearsExperience: 4, verified: true, endorsements: 34 },
      { name: 'System Design', level: 'advanced', yearsExperience: 3, verified: false },
      { name: 'Team Leadership', level: 'intermediate', yearsExperience: 2, verified: false },
    ],
    experience: [
      {
        id: 'exp-004',
        company: 'Tech Company XYZ',
        role: 'Senior Software Engineer',
        startDate: new Date('2022-01-01'),
        isCurrent: true,
        description: 'Tech lead de equipa de 5 developers. Responsável pela arquitetura de microserviços.',
        achievements: [
          'Liderou migração para arquitetura cloud-native',
          'Reduziu latência do sistema em 40%',
          'Mentor de 3 junior developers',
        ],
        companyType: 'scaleup',
        companySize: '100-500',
        industry: 'Technology',
        location: 'Lisboa, Portugal',
      },
      {
        id: 'exp-005',
        company: 'Digital Agency Pro',
        role: 'Full Stack Developer',
        startDate: new Date('2018-06-01'),
        endDate: new Date('2021-12-31'),
        isCurrent: false,
        description: 'Desenvolvimento de aplicações web para clientes enterprise.',
        achievements: [
          'Desenvolveu +15 projetos para clientes Fortune 500',
          'Stack: React, Node.js, PostgreSQL',
        ],
        companyType: 'agency',
        companySize: '50-100',
        industry: 'Digital Agency',
        location: 'Lisboa, Portugal',
      },
    ],
    education: [
      {
        id: 'edu-003',
        institution: 'Instituto Superior Técnico',
        degree: 'Mestrado',
        field: 'Engenharia Informática',
        startDate: new Date('2014-09-01'),
        endDate: new Date('2017-06-30'),
        grade: '18/20',
      },
    ],
    languages: [
      { name: 'Português', level: 'native' },
      { name: 'Inglês', level: 'fluent' },
    ],
    linkedinUrl: 'https://linkedin.com/in/ricardodev',
    source: 'linkedin',
    status: 'in_process',
    aiScore: 92,
    aiAnalysis: {
      id: 'analysis-002',
      candidateId: 'cand-002',
      generatedAt: new Date('2025-05-20'),
      summary: 'Senior Software Engineer com forte background em React e Node.js. Experiência em arquitetura de microserviços e cloud. Potencial para evolução para Tech Lead ou Engineering Manager.',
      seniorityLevel: 'senior',
      specializations: ['Full Stack', 'React', 'Microservices', 'Cloud Architecture'],
      strengths: [
        {
          category: 'Technical Depth',
          description: 'Profundo conhecimento em stack moderno',
          evidence: ['React expert', 'AWS certified', 'Microservices architecture'],
          confidence: 94,
        },
        {
          category: 'Leadership Potential',
          description: 'Experiência inicial de liderança técnica',
          evidence: ['Tech lead de equipa', 'Mentoria de juniors'],
          confidence: 82,
        },
      ],
      gaps: [
        {
          category: 'Management Experience',
          description: 'Experiência limitada em gestão formal de equipas',
          evidence: ['Apenas 2 anos como tech lead informal'],
          confidence: 70,
        },
      ],
      riskSignals: [],
      culturalFitIndicators: [
        { dimension: 'Technical Excellence', score: 95, indicators: ['Qualidade de código', 'Best practices'] },
        { dimension: 'Collaboration', score: 88, indicators: ['Mentoria', 'Code reviews'] },
      ],
      careerTrajectory: 'ascending',
      marketValue: 'above',
      recommendations: [
        'Forte candidato para Senior Engineer ou Tech Lead',
        'Potencial para Engineering Manager com desenvolvimento',
      ],
      similarProfiles: ['cand-008'],
      matchScores: [
        { jobId: 'job-001', jobTitle: 'Senior Software Engineer', score: 92, matchedCriteria: ['React', 'Node.js', 'Cloud'], missingCriteria: [] },
      ],
    },
    scorecards: [],
    notes: [],
    interactions: [],
    tags: ['Tech', 'React', 'Node.js', 'Senior'],
    starred: true,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-20'),
  },
  {
    id: 'cand-003',
    name: 'Carla Mendes',
    email: 'carla.mendes@email.com',
    phone: '+351 923 456 789',
    currentRole: 'Marketing Director',
    currentCompany: 'Global Marketing Inc',
    location: 'Porto, Portugal',
    yearsExperience: 12,
    skills: [
      { name: 'Digital Marketing', level: 'expert', yearsExperience: 10, verified: true, endorsements: 56 },
      { name: 'Brand Strategy', level: 'expert', yearsExperience: 8, verified: true, endorsements: 42 },
      { name: 'Team Leadership', level: 'expert', yearsExperience: 6, verified: true, endorsements: 38 },
      { name: 'Performance Marketing', level: 'advanced', yearsExperience: 5, verified: true },
      { name: 'Content Strategy', level: 'advanced', yearsExperience: 7, verified: true },
    ],
    experience: [
      {
        id: 'exp-006',
        company: 'Global Marketing Inc',
        role: 'Marketing Director',
        startDate: new Date('2020-04-01'),
        isCurrent: true,
        description: 'Liderança de equipa de 15 pessoas. Responsável por estratégia de marketing para região Ibérica.',
        achievements: [
          'Crescimento de 180% em leads qualificados',
          'Implementação de stack MarTech completo',
          'Budget de €2M/ano',
        ],
        companyType: 'corporate',
        companySize: '500-1000',
        industry: 'Marketing & Advertising',
        location: 'Porto, Portugal',
      },
    ],
    education: [
      {
        id: 'edu-004',
        institution: 'Porto Business School',
        degree: 'MBA',
        field: 'Marketing Management',
        startDate: new Date('2015-09-01'),
        endDate: new Date('2017-06-30'),
      },
    ],
    languages: [
      { name: 'Português', level: 'native' },
      { name: 'Inglês', level: 'fluent' },
      { name: 'Espanhol', level: 'fluent' },
    ],
    linkedinUrl: 'https://linkedin.com/in/carlamendes',
    source: 'referral',
    status: 'in_process',
    aiScore: 88,
    aiAnalysis: {
      id: 'analysis-003',
      candidateId: 'cand-003',
      generatedAt: new Date('2025-05-18'),
      summary: 'Marketing Director com sólida experiência em B2B e mercados Ibéricos. Forte capacidade de liderança e track record em crescimento de negócio através de marketing.',
      seniorityLevel: 'executive',
      specializations: ['B2B Marketing', 'Brand Strategy', 'Team Leadership', 'MarTech'],
      strengths: [
        {
          category: 'Results Driven',
          description: 'Track record comprovado de crescimento',
          evidence: ['180% crescimento em leads', 'ROI positivo em campanhas'],
          confidence: 90,
        },
      ],
      gaps: [],
      riskSignals: [],
      culturalFitIndicators: [
        { dimension: 'Leadership', score: 90, indicators: ['Gestão de equipa de 15', 'Desenvolvimento de pessoas'] },
      ],
      careerTrajectory: 'ascending',
      marketValue: 'market',
      recommendations: ['Ideal para posições de Marketing Director ou CMO em scale-ups'],
      similarProfiles: [],
      matchScores: [
        { jobId: 'job-002', jobTitle: 'Marketing Manager', score: 88, matchedCriteria: ['Digital Marketing', 'Team Leadership'], missingCriteria: [] },
      ],
    },
    scorecards: [],
    notes: [],
    interactions: [],
    tags: ['Marketing', 'Director', 'B2B', 'Referral'],
    starred: true,
    createdAt: new Date('2025-05-08'),
    updatedAt: new Date('2025-05-18'),
  },
  {
    id: 'cand-004',
    name: 'Ana Ferreira',
    email: 'ana.ferreira@email.com',
    phone: '+351 945 678 901',
    currentRole: 'UX Lead',
    currentCompany: 'Design Studio',
    location: 'Remoto',
    yearsExperience: 6,
    skills: [
      { name: 'Figma', level: 'expert', yearsExperience: 5, verified: true, endorsements: 89 },
      { name: 'User Research', level: 'advanced', yearsExperience: 4, verified: true, endorsements: 45 },
      { name: 'Design Systems', level: 'expert', yearsExperience: 3, verified: true, endorsements: 38 },
      { name: 'Prototyping', level: 'expert', yearsExperience: 5, verified: true },
      { name: 'Usability Testing', level: 'advanced', yearsExperience: 4, verified: false },
    ],
    experience: [
      {
        id: 'exp-007',
        company: 'Design Studio',
        role: 'UX Lead',
        startDate: new Date('2022-09-01'),
        isCurrent: true,
        description: 'Liderança de projectos de UX/UI para clientes enterprise. Definição de design systems.',
        achievements: [
          'Criou design system utilizado por +10 produtos',
          'Liderou redesign que aumentou conversão em 35%',
        ],
        companyType: 'agency',
        companySize: '20-50',
        industry: 'Design',
        location: 'Remoto',
      },
    ],
    education: [
      {
        id: 'edu-005',
        institution: 'IADE',
        degree: 'Licenciatura',
        field: 'Design de Comunicação',
        startDate: new Date('2015-09-01'),
        endDate: new Date('2019-06-30'),
      },
    ],
    languages: [
      { name: 'Português', level: 'native' },
      { name: 'Inglês', level: 'fluent' },
    ],
    linkedinUrl: 'https://linkedin.com/in/anaferreira-ux',
    portfolioUrl: 'https://anaferreira.design',
    source: 'talent_pool',
    status: 'talent_pool',
    aiScore: 78,
    aiAnalysis: {
      id: 'analysis-004',
      candidateId: 'cand-004',
      generatedAt: new Date('2025-04-10'),
      summary: 'UX Lead com forte portfolio e experiência em design systems. Ideal para posições de product design em empresas de produto.',
      seniorityLevel: 'senior',
      specializations: ['UX Design', 'Design Systems', 'User Research'],
      strengths: [
        {
          category: 'Design Skills',
          description: 'Forte domínio de ferramentas e metodologias',
          evidence: ['Expert em Figma', 'Design system para +10 produtos'],
          confidence: 92,
        },
      ],
      gaps: [
        {
          category: 'Product Experience',
          description: 'Maioria da experiência em agência vs in-house',
          evidence: ['Carreira em agências'],
          confidence: 65,
        },
      ],
      riskSignals: [],
      culturalFitIndicators: [
        { dimension: 'Creativity', score: 95, indicators: ['Portfolio diversificado'] },
        { dimension: 'Collaboration', score: 85, indicators: ['Trabalho com developers'] },
      ],
      careerTrajectory: 'ascending',
      marketValue: 'market',
      recommendations: ['Potencial para posições de Senior/Lead Product Designer'],
      similarProfiles: [],
      matchScores: [],
    },
    scorecards: [],
    notes: [],
    interactions: [],
    tags: ['UX', 'Design', 'Figma', 'Talent Pool'],
    starred: false,
    createdAt: new Date('2025-04-10'),
    updatedAt: new Date('2025-04-10'),
  },
  {
    id: 'cand-005',
    name: 'Miguel Santos',
    email: 'miguel.santos@email.com',
    phone: '+351 956 789 012',
    currentRole: 'Sales Director',
    currentCompany: 'Enterprise Solutions',
    location: 'Lisboa, Portugal',
    yearsExperience: 10,
    skills: [
      { name: 'B2B Sales', level: 'expert', yearsExperience: 10, verified: true, endorsements: 67 },
      { name: 'Team Management', level: 'expert', yearsExperience: 6, verified: true, endorsements: 45 },
      { name: 'Negotiation', level: 'expert', yearsExperience: 10, verified: true, endorsements: 52 },
      { name: 'CRM', level: 'advanced', yearsExperience: 8, verified: true },
      { name: 'Enterprise Sales', level: 'expert', yearsExperience: 7, verified: true },
    ],
    experience: [
      {
        id: 'exp-008',
        company: 'Enterprise Solutions',
        role: 'Sales Director',
        startDate: new Date('2021-01-01'),
        isCurrent: true,
        description: 'Liderança de equipa comercial de 12 pessoas. Pipeline de €15M.',
        achievements: [
          'Crescimento de 140% em revenue',
          'Fechou 3 deals enterprise >€500K',
          'Expandiu equipa de 5 para 12',
        ],
        companyType: 'scaleup',
        companySize: '100-500',
        industry: 'Enterprise Software',
        location: 'Lisboa, Portugal',
      },
    ],
    education: [
      {
        id: 'edu-006',
        institution: 'Católica Lisbon',
        degree: 'MBA',
        field: 'Business Administration',
        startDate: new Date('2016-09-01'),
        endDate: new Date('2018-06-30'),
      },
    ],
    languages: [
      { name: 'Português', level: 'native' },
      { name: 'Inglês', level: 'fluent' },
      { name: 'Espanhol', level: 'professional' },
    ],
    linkedinUrl: 'https://linkedin.com/in/miguelsantos-sales',
    source: 'linkedin',
    status: 'in_process',
    aiScore: 85,
    aiAnalysis: {
      id: 'analysis-005',
      candidateId: 'cand-005',
      generatedAt: new Date('2025-05-21'),
      summary: 'Sales Director com track record impressionante em vendas enterprise B2B. Forte capacidade de construção e liderança de equipas comerciais.',
      seniorityLevel: 'executive',
      specializations: ['Enterprise Sales', 'B2B', 'Team Building', 'Strategic Accounts'],
      strengths: [
        {
          category: 'Sales Performance',
          description: 'Track record excepcional de crescimento',
          evidence: ['140% crescimento em revenue', 'Deals >€500K'],
          confidence: 95,
        },
        {
          category: 'Team Building',
          description: 'Capacidade comprovada de scaling de equipas',
          evidence: ['Crescimento de 5 para 12 pessoas'],
          confidence: 88,
        },
      ],
      gaps: [],
      riskSignals: [],
      culturalFitIndicators: [
        { dimension: 'Results Orientation', score: 96, indicators: ['KPIs excedidos', 'Revenue growth'] },
        { dimension: 'Leadership', score: 90, indicators: ['Team growth', 'Coaching'] },
      ],
      careerTrajectory: 'ascending',
      marketValue: 'above',
      recommendations: ['Forte candidato para VP Sales ou Sales Director em scale-up'],
      similarProfiles: [],
      matchScores: [
        { jobId: 'job-005', jobTitle: 'Sales Director', score: 85, matchedCriteria: ['B2B Sales', 'Team Leadership', 'Enterprise'], missingCriteria: [] },
      ],
    },
    scorecards: [],
    notes: [],
    interactions: [],
    tags: ['Sales', 'Director', 'B2B', 'Enterprise'],
    starred: true,
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2025-05-21'),
  },
]

// ==========================================
// JOB POSITIONS
// ==========================================
export const jobPositions: JobPosition[] = [
  {
    id: 'job-001',
    title: 'Senior Software Engineer',
    department: 'Engenharia',
    location: 'Lisboa, Portugal',
    type: 'full_time',
    level: 'senior',
    salaryRange: { min: 55000, max: 75000, currency: 'EUR' },
    description: 'Procuramos um Senior Software Engineer para integrar a nossa equipa de produto. Responsável por arquitetura e desenvolvimento de features core da plataforma.',
    requirements: [
      { type: 'skill', description: 'React/TypeScript', mandatory: true, minYears: 4 },
      { type: 'skill', description: 'Node.js', mandatory: true, minYears: 3 },
      { type: 'skill', description: 'Cloud (AWS/GCP)', mandatory: true, minYears: 2 },
      { type: 'experience', description: 'Experiência em produtos SaaS', mandatory: true, minYears: 3 },
      { type: 'skill', description: 'System Design', mandatory: false },
    ],
    niceToHave: ['Kubernetes', 'GraphQL', 'Experiência em startups'],
    benefits: ['Remote-first', 'Stock options', 'Budget de formação', 'Seguro de saúde'],
    hiringManager: { id: 'hm-001', name: 'João Silva', email: 'joao.silva@empresa.pt' },
    status: 'active',
    priority: 'high',
    targetCompanies: ['Tech Company XYZ', 'Startup ABC', 'OutSystems', 'Farfetch'],
    candidates: ['cand-002'],
    pipeline: [
      { id: 'stage-1', name: 'Candidatura', order: 1, type: 'sourcing', candidateIds: [], avgDaysInStage: 2 },
      { id: 'stage-2', name: 'Triagem', order: 2, type: 'screening', candidateIds: [], avgDaysInStage: 3 },
      { id: 'stage-3', name: 'Entrevista RH', order: 3, type: 'interview', candidateIds: [], avgDaysInStage: 5 },
      { id: 'stage-4', name: 'Entrevista Técnica', order: 4, type: 'interview', candidateIds: ['cand-002'], avgDaysInStage: 4 },
      { id: 'stage-5', name: 'Entrevista Final', order: 5, type: 'interview', candidateIds: [], avgDaysInStage: 3 },
      { id: 'stage-6', name: 'Proposta', order: 6, type: 'offer', candidateIds: [], avgDaysInStage: 5 },
    ],
    aiSourcingEnabled: true,
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2025-05-22'),
  },
  {
    id: 'job-002',
    title: 'Marketing Manager',
    department: 'Marketing',
    location: 'Porto, Portugal',
    type: 'full_time',
    level: 'senior',
    salaryRange: { min: 45000, max: 60000, currency: 'EUR' },
    description: 'Procuramos Marketing Manager para liderar estratégia de marketing digital e brand.',
    requirements: [
      { type: 'skill', description: 'Digital Marketing', mandatory: true, minYears: 5 },
      { type: 'skill', description: 'Team Leadership', mandatory: true, minYears: 2 },
      { type: 'experience', description: 'Experiência em B2B', mandatory: true },
    ],
    niceToHave: ['Experiência em SaaS', 'Growth hacking'],
    benefits: ['Híbrido', 'Bónus anual', 'Budget de formação'],
    hiringManager: { id: 'hm-002', name: 'Ana Costa', email: 'ana.costa@empresa.pt' },
    status: 'active',
    priority: 'medium',
    candidates: ['cand-003'],
    pipeline: [
      { id: 'stage-1', name: 'Candidatura', order: 1, type: 'sourcing', candidateIds: [] },
      { id: 'stage-2', name: 'Triagem', order: 2, type: 'screening', candidateIds: [] },
      { id: 'stage-3', name: 'Entrevista RH', order: 3, type: 'interview', candidateIds: [] },
      { id: 'stage-4', name: 'Entrevista Final', order: 4, type: 'interview', candidateIds: ['cand-003'] },
      { id: 'stage-5', name: 'Proposta', order: 5, type: 'offer', candidateIds: [] },
    ],
    aiSourcingEnabled: true,
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-18'),
  },
  {
    id: 'job-003',
    title: 'CFO - Chief Financial Officer',
    department: 'Executivo',
    location: 'Lisboa, Portugal',
    type: 'full_time',
    level: 'c_level',
    salaryRange: { min: 120000, max: 180000, currency: 'EUR' },
    description: 'Procuramos CFO para liderar a função financeira da empresa em fase de preparação para IPO.',
    requirements: [
      { type: 'experience', description: 'Experiência como CFO ou VP Finance', mandatory: true, minYears: 5 },
      { type: 'skill', description: 'IPO preparation', mandatory: true },
      { type: 'skill', description: 'M&A', mandatory: false },
      { type: 'experience', description: 'Experiência em tech/startup', mandatory: true },
    ],
    niceToHave: ['Big Four background', 'Experiência internacional'],
    benefits: ['Equity package', 'Board participation', 'Seguro executivo'],
    hiringManager: { id: 'hm-003', name: 'Pedro Ferreira', email: 'pedro.ferreira@empresa.pt' },
    status: 'active',
    priority: 'high',
    targetCompanies: ['Farfetch', 'OutSystems', 'Talkdesk', 'Remote', 'Anchorage Digital'],
    candidates: ['cand-001'],
    pipeline: [
      { id: 'stage-1', name: 'Sourcing', order: 1, type: 'sourcing', candidateIds: [] },
      { id: 'stage-2', name: 'Screening', order: 2, type: 'screening', candidateIds: [] },
      { id: 'stage-3', name: 'Entrevista HR', order: 3, type: 'interview', candidateIds: [] },
      { id: 'stage-4', name: 'Entrevista CEO', order: 4, type: 'interview', candidateIds: ['cand-001'] },
      { id: 'stage-5', name: 'Board Interview', order: 5, type: 'interview', candidateIds: [] },
      { id: 'stage-6', name: 'Proposta', order: 6, type: 'offer', candidateIds: [] },
    ],
    aiSourcingEnabled: true,
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-05-22'),
  },
  {
    id: 'job-005',
    title: 'Sales Director',
    department: 'Vendas',
    location: 'Lisboa, Portugal',
    type: 'full_time',
    level: 'director',
    salaryRange: { min: 70000, max: 100000, currency: 'EUR' },
    description: 'Procuramos Sales Director para liderar a equipa comercial e expandir mercado Ibérico.',
    requirements: [
      { type: 'experience', description: 'Experiência como Sales Director/Manager', mandatory: true, minYears: 5 },
      { type: 'skill', description: 'B2B Enterprise Sales', mandatory: true },
      { type: 'skill', description: 'Team Leadership', mandatory: true, minYears: 3 },
    ],
    niceToHave: ['Experiência SaaS', 'Network no mercado Ibérico'],
    benefits: ['Comissões atrativas', 'Carro empresa', 'Stock options'],
    hiringManager: { id: 'hm-004', name: 'Miguel Santos', email: 'miguel.santos@empresa.pt' },
    status: 'active',
    priority: 'high',
    candidates: ['cand-005'],
    pipeline: [
      { id: 'stage-1', name: 'Candidatura', order: 1, type: 'sourcing', candidateIds: [] },
      { id: 'stage-2', name: 'Triagem', order: 2, type: 'screening', candidateIds: [] },
      { id: 'stage-3', name: 'Entrevista RH', order: 3, type: 'interview', candidateIds: [] },
      { id: 'stage-4', name: 'Entrevista VP', order: 4, type: 'interview', candidateIds: [] },
      { id: 'stage-5', name: 'Proposta', order: 5, type: 'offer', candidateIds: ['cand-005'] },
    ],
    aiSourcingEnabled: true,
    createdAt: new Date('2025-05-15'),
    updatedAt: new Date('2025-05-21'),
  },
]

// ==========================================
// SOURCING STRATEGIES
// ==========================================
export const sourcingStrategies: SourcingStrategy[] = [
  {
    id: 'strat-001',
    jobId: 'job-003',
    targetProfiles: [
      {
        description: 'CFO experiente de tech startup com background em IPO',
        traits: ['Strategic thinker', 'Hands-on', 'Startup mindset', 'Investor relations'],
        mustHave: ['IPO experience', 'CFO/VP Finance role', 'Tech industry'],
        niceToHave: ['Big Four', 'International experience', 'M&A'],
        dealBreakers: ['Only corporate experience', 'No tech background'],
      },
    ],
    booleanSearches: [
      {
        platform: 'linkedin',
        query: '(CFO OR "Chief Financial Officer" OR "VP Finance" OR "Vice President Finance") AND (IPO OR "public offering" OR "Series C" OR "Series D") AND (tech OR technology OR SaaS OR software) AND (Portugal OR Lisboa OR Lisbon)',
        explanation: 'Pesquisa focada em executivos financeiros seniores com experiência em IPO no sector tech em Portugal',
        expectedResults: 150,
      },
      {
        platform: 'linkedin',
        query: '("Finance Director" OR CFO) AND (startup OR scale-up OR scaleup) AND (Portugal OR remote) AND ("venture capital" OR VC OR funding)',
        explanation: 'Pesquisa alternativa focada em ambiente startup e funding',
        expectedResults: 85,
      },
    ],
    targetCompanies: [
      { name: 'Farfetch', reason: 'Tech unicorn português, provável pool de talento C-level', relevantRoles: ['CFO', 'VP Finance', 'Finance Director'], priority: 'high' },
      { name: 'OutSystems', reason: 'Empresa tech portuguesa com experiência em funding rounds', relevantRoles: ['Finance Leadership'], priority: 'high' },
      { name: 'Talkdesk', reason: 'Unicorn com HQ em Lisboa', relevantRoles: ['CFO', 'VP Finance'], priority: 'high' },
      { name: 'Remote', reason: 'Unicorn com presença em Portugal', relevantRoles: ['Finance team'], priority: 'medium' },
      { name: 'Big Four Portugal', reason: 'Pool de talento com skills técnicas', relevantRoles: ['Partner', 'Director'], priority: 'medium' },
    ],
    equivalentTitles: ['CFO', 'Chief Financial Officer', 'VP Finance', 'Vice President Finance', 'Finance Director', 'Head of Finance'],
    industryFocus: ['Technology', 'SaaS', 'Fintech', 'E-commerce'],
    geographyFocus: ['Portugal', 'Spain', 'Remote EMEA'],
    seniorityRange: ['C-Level', 'VP', 'Director'],
    aiRecommendations: [
      { type: 'company', suggestion: 'Considerar alumni de Revolut Portugal', reasoning: 'Fintech de alto crescimento com talento financeiro qualificado', confidence: 85 },
      { type: 'title', suggestion: 'Incluir "Head of FP&A" na pesquisa', reasoning: 'Muitos CFOs atuais vieram de background em FP&A', confidence: 78 },
      { type: 'strategy', suggestion: 'Expandir pesquisa para CFOs de Series B startups', reasoning: 'Podem estar prontos para próximo step em empresa maior', confidence: 82 },
    ],
    generatedAt: new Date('2025-05-20'),
  },
]

// ==========================================
// OUTREACH CAMPAIGNS
// ==========================================
export const outreachCampaigns: OutreachCampaign[] = [
  {
    id: 'campaign-001',
    name: 'CFO Search - Executive Outreach',
    jobId: 'job-003',
    status: 'active',
    type: 'cold',
    templates: [
      {
        id: 'template-001',
        name: 'Initial InMail',
        channel: 'inmail',
        subject: 'Oportunidade de CFO em Tech Unicorn Português',
        content: `Olá {{firstName}},

Espero que esta mensagem o encontre bem. O meu nome é {{senderName}} e estou a trabalhar num processo confidencial de Executive Search.

Estamos a identificar candidatos para uma posição de CFO numa das empresas tech portuguesas de maior crescimento, atualmente em preparação para IPO.

O seu perfil em {{currentCompany}} e experiência em {{relevantExperience}} chamaram a nossa atenção.

Teria disponibilidade para uma breve chamada de 15 minutos esta semana para partilhar mais detalhes?

Cumprimentos,
{{senderName}}`,
        variables: ['firstName', 'senderName', 'currentCompany', 'relevantExperience'],
        sequence: 1,
        delayDays: 0,
        isAIGenerated: true,
      },
      {
        id: 'template-002',
        name: 'Follow-up 1',
        channel: 'inmail',
        subject: 'Re: Oportunidade de CFO',
        content: `Olá {{firstName}},

Espero não estar a ser inconveniente. Gostaria de dar seguimento à minha mensagem anterior.

A posição de CFO que mencionei representa uma oportunidade única de liderar a função financeira numa empresa que já fechou um Series C significativo e está no caminho para IPO nos próximos 18-24 meses.

Mesmo que não seja o timing ideal para si, ficaria grato se pudéssemos trocar ideias sobre o mercado.

Cumprimentos,
{{senderName}}`,
        variables: ['firstName', 'senderName'],
        sequence: 2,
        delayDays: 5,
        isAIGenerated: true,
      },
    ],
    recipients: [
      { candidateId: 'cand-001', candidateName: 'Bruno Costa', currentStage: 1, status: 'replied', sentAt: new Date('2025-05-15'), openedAt: new Date('2025-05-15'), repliedAt: new Date('2025-05-16'), response: 'interested' },
    ],
    stats: {
      totalSent: 28,
      opened: 22,
      openRate: 78.6,
      clicked: 0,
      clickRate: 0,
      replied: 12,
      replyRate: 42.9,
      interested: 8,
      interestRate: 28.6,
    },
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-22'),
  },
]

// ==========================================
// MARKET INTELLIGENCE
// ==========================================
export const marketIntelligence: MarketIntelligence[] = [
  {
    id: 'intel-001',
    type: 'funding',
    company: 'Startup Portuguesa ABC',
    headline: 'Startup ABC fecha Series C de €50M',
    description: 'A Startup ABC, empresa portuguesa de software B2B, fechou uma ronda Series C de €50 milhões liderada por Sequoia Capital. A empresa planeia duplicar a equipa em 2025.',
    source: 'TechCrunch',
    sourceUrl: 'https://techcrunch.com/startup-abc-series-c',
    date: new Date('2025-05-20'),
    relevantFor: ['job-001', 'job-003'],
    talentOpportunity: 'Empresa em crescimento acelerado - potenciais saídas de talento após vesting ou interessados em novas oportunidades',
    affectedRoles: ['Engineering', 'Product', 'Finance'],
    estimatedImpact: 'high',
  },
  {
    id: 'intel-002',
    type: 'layoff',
    company: 'Tech Giant XYZ',
    headline: 'Tech Giant XYZ anuncia reestruturação - 500 posições afetadas em EMEA',
    description: 'A Tech Giant XYZ anunciou uma reestruturação que afeta 500 posições na região EMEA, incluindo escritório de Lisboa. Equipas de engineering e sales são as mais afetadas.',
    source: 'LinkedIn News',
    date: new Date('2025-05-18'),
    relevantFor: ['job-001', 'job-005'],
    talentOpportunity: 'Pool significativo de talento sénior disponível no mercado português',
    affectedRoles: ['Senior Engineers', 'Sales Leadership', 'Product Managers'],
    estimatedImpact: 'high',
  },
  {
    id: 'intel-003',
    type: 'leadership_change',
    company: 'Fintech Leader',
    headline: 'CFO da Fintech Leader anuncia saída após 5 anos',
    description: 'O CFO da Fintech Leader, João Marques, anunciou a sua saída após liderar a empresa através de um IPO bem-sucedido. Não anunciou próximos passos.',
    source: 'Jornal de Negócios',
    date: new Date('2025-05-15'),
    relevantFor: ['job-003'],
    talentOpportunity: 'Potencial candidato para posições de CFO - experiência IPO recente',
    affectedRoles: ['CFO'],
    estimatedImpact: 'medium',
  },
  {
    id: 'intel-004',
    type: 'expansion',
    company: 'US Tech Company',
    headline: 'US Tech Company abre hub em Lisboa com 200 posições',
    description: 'A US Tech Company anunciou a abertura de um hub de engenharia em Lisboa, com planos de contratar 200 engenheiros nos próximos 18 meses.',
    source: 'Público',
    date: new Date('2025-05-12'),
    relevantFor: ['job-001'],
    talentOpportunity: 'Concorrência aumentada por talento tech - ajustar pacotes de compensação',
    affectedRoles: ['Software Engineers'],
    estimatedImpact: 'high',
  },
  {
    id: 'intel-005',
    type: 'hiring_surge',
    company: 'Scale-up PT',
    headline: 'Scale-up PT duplica equipa comercial',
    description: 'A Scale-up PT está em processo de expansão agressiva da equipa comercial, tendo contratado 15 pessoas nos últimos 2 meses.',
    source: 'ECO',
    date: new Date('2025-05-08'),
    relevantFor: ['job-005'],
    talentOpportunity: 'Potencial fonte de leads - colaboradores que não se adaptaram ou estão abertos',
    affectedRoles: ['Sales'],
    estimatedImpact: 'medium',
  },
]

// ==========================================
// COMPANY PROFILES
// ==========================================
export const companyProfiles: CompanyProfile[] = [
  {
    id: 'company-001',
    name: 'Farfetch',
    industry: 'E-commerce / Fashion Tech',
    size: '5000+',
    headquarters: 'London, UK (com escritório em Porto)',
    description: 'Plataforma global de luxo que liga criadores, curadores e consumidores.',
    linkedinUrl: 'https://linkedin.com/company/farfetch',
    websiteUrl: 'https://farfetch.com',
    fundingStage: 'public',
    keyPeople: [
      { name: 'José Neves', role: 'Founder & CEO', linkedinUrl: 'https://linkedin.com/in/joseneves', tenure: '15+ anos' },
    ],
    recentNews: [],
    hiringTrends: [
      { role: 'Software Engineer', trend: 'stable', openPositions: 25 },
      { role: 'Product Manager', trend: 'increasing', openPositions: 8 },
    ],
    talentPoolSize: 45,
    competitorOf: ['YOOX Net-a-Porter', 'Mytheresa'],
  },
  {
    id: 'company-002',
    name: 'OutSystems',
    industry: 'Enterprise Software / Low-Code',
    size: '2000-5000',
    headquarters: 'Lisboa, Portugal',
    description: 'Plataforma líder de low-code para desenvolvimento de aplicações enterprise.',
    linkedinUrl: 'https://linkedin.com/company/outsystems',
    websiteUrl: 'https://outsystems.com',
    fundingStage: 'late_stage',
    totalFunding: 430000000,
    lastFundingDate: new Date('2021-06-01'),
    keyPeople: [
      { name: 'Paulo Rosado', role: 'Founder & CEO', linkedinUrl: 'https://linkedin.com/in/paulorosado', tenure: '20+ anos' },
    ],
    recentNews: [],
    hiringTrends: [
      { role: 'Software Engineer', trend: 'increasing', openPositions: 40 },
      { role: 'Sales', trend: 'stable', openPositions: 15 },
    ],
    talentPoolSize: 62,
    competitorOf: ['Mendix', 'ServiceNow', 'Microsoft Power Platform'],
  },
]

// ==========================================
// TALENT POOLS
// ==========================================
export const talentPools: TalentPool[] = [
  {
    id: 'pool-001',
    name: 'Senior Engineers - React/Node',
    description: 'Pool de engenheiros seniores com experiência em React e Node.js',
    criteria: {
      skills: ['React', 'Node.js', 'TypeScript'],
      seniorityLevels: ['senior', 'lead'],
      locations: ['Portugal', 'Remote'],
      minExperience: 5,
    },
    candidateIds: ['cand-002', 'cand-004'],
    isSmartPool: true,
    autoUpdate: true,
    createdBy: 'Maria Santos',
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-05-22'),
  },
  {
    id: 'pool-002',
    name: 'C-Level Finance',
    description: 'Executivos financeiros para posições de CFO e VP Finance',
    criteria: {
      roles: ['CFO', 'VP Finance', 'Finance Director'],
      seniorityLevels: ['executive', 'c-level'],
      industries: ['Technology', 'Fintech', 'SaaS'],
    },
    candidateIds: ['cand-001'],
    isSmartPool: true,
    autoUpdate: true,
    createdBy: 'Maria Santos',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-05-20'),
  },
  {
    id: 'pool-003',
    name: 'Marketing Leaders',
    description: 'Líderes de marketing digital e brand',
    criteria: {
      skills: ['Digital Marketing', 'Brand Strategy', 'Team Leadership'],
      seniorityLevels: ['senior', 'director', 'executive'],
    },
    candidateIds: ['cand-003'],
    isSmartPool: false,
    autoUpdate: false,
    createdBy: 'Maria Santos',
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-05-18'),
  },
]

// ==========================================
// SEMANTIC SEARCH EXAMPLES
// ==========================================
export const semanticSearchExamples: SemanticSearchQuery[] = [
  {
    id: 'search-001',
    query: 'Executivos com experiência em expansão internacional SaaS',
    interpretation: 'Procura por perfis executivos (C-level, VP, Director) com histórico de liderar ou participar em expansão internacional de empresas SaaS',
    extractedEntities: [
      { type: 'role', value: 'Executive', confidence: 95 },
      { type: 'experience', value: 'International expansion', confidence: 90 },
      { type: 'industry', value: 'SaaS', confidence: 98 },
    ],
    results: [
      {
        candidateId: 'cand-001',
        candidateName: 'Bruno Costa',
        currentRole: 'CFO',
        currentCompany: 'Startup ABC',
        matchScore: 85,
        matchReasons: ['C-Level executive', 'SaaS company', 'IPO preparation involves international investors'],
        highlights: [
          { field: 'experience', content: 'Liderou Series B de €25M com investidores internacionais', matchedTerms: ['internacional'] },
        ],
      },
      {
        candidateId: 'cand-003',
        candidateName: 'Carla Mendes',
        currentRole: 'Marketing Director',
        currentCompany: 'Global Marketing Inc',
        matchScore: 72,
        matchReasons: ['Director level', 'Iberian market experience'],
        highlights: [
          { field: 'experience', content: 'Estratégia de marketing para região Ibérica', matchedTerms: ['expansão', 'internacional'] },
        ],
      },
    ],
    totalResults: 2,
    searchedAt: new Date('2025-05-22'),
  },
  {
    id: 'search-002',
    query: 'Perfis semelhantes a CTO com background em microserviços',
    interpretation: 'Procura por perfis técnicos seniores com forte experiência em arquitetura de microserviços, potenciais CTOs ou Tech Leads',
    extractedEntities: [
      { type: 'role', value: 'CTO/Tech Lead', confidence: 90 },
      { type: 'skill', value: 'Microservices architecture', confidence: 95 },
    ],
    results: [
      {
        candidateId: 'cand-002',
        candidateName: 'Ricardo Neves',
        currentRole: 'Senior Software Engineer',
        currentCompany: 'Tech Company XYZ',
        matchScore: 88,
        matchReasons: ['Tech Lead experience', 'Microservices architecture', 'Cloud-native migration'],
        highlights: [
          { field: 'achievements', content: 'Liderou migração para arquitetura cloud-native', matchedTerms: ['microserviços', 'arquitetura'] },
        ],
      },
    ],
    totalResults: 1,
    searchedAt: new Date('2025-05-21'),
  },
]

// ==========================================
// RECRUITMENT ANALYTICS
// ==========================================
export const recruitmentAnalytics: RecruitmentAnalytics = {
  period: 'month',
  startDate: new Date('2025-05-01'),
  endDate: new Date('2025-05-31'),
  overview: {
    totalCandidates: 245,
    newCandidates: 67,
    candidatesInProcess: 38,
    hired: 3,
    rejected: 24,
    timeToHire: 32,
    offerAcceptanceRate: 85,
    costPerHire: 4500,
  },
  sourcing: {
    bySource: [
      { source: 'LinkedIn', count: 120, hiredCount: 1, conversionRate: 0.8 },
      { source: 'AI Sourcing', count: 45, hiredCount: 1, conversionRate: 2.2 },
      { source: 'Referral', count: 35, hiredCount: 1, conversionRate: 2.9 },
      { source: 'Direct Application', count: 30, hiredCount: 0, conversionRate: 0 },
      { source: 'Executive Search', count: 15, hiredCount: 0, conversionRate: 0 },
    ],
    byChannel: [
      { channel: 'LinkedIn InMail', count: 89, responseRate: 42 },
      { channel: 'Email', count: 45, responseRate: 28 },
      { channel: 'Phone', count: 20, responseRate: 65 },
    ],
    topPerformingSearches: [
      { query: 'Senior React Engineer Portugal', resultsFound: 85, hired: 1 },
      { query: 'CFO IPO experience tech', resultsFound: 12, hired: 0 },
    ],
    aiSourcingEfficiency: 78,
  },
  pipeline: {
    byStage: [
      { stage: 'Candidatura', count: 67, avgDays: 2, dropoffRate: 40 },
      { stage: 'Triagem', count: 40, avgDays: 3, dropoffRate: 25 },
      { stage: 'Entrevista RH', count: 30, avgDays: 5, dropoffRate: 20 },
      { stage: 'Entrevista Técnica', count: 24, avgDays: 7, dropoffRate: 30 },
      { stage: 'Entrevista Final', count: 17, avgDays: 4, dropoffRate: 15 },
      { stage: 'Proposta', count: 14, avgDays: 6, dropoffRate: 20 },
      { stage: 'Contratado', count: 3, avgDays: 0, dropoffRate: 0 },
    ],
    bottlenecks: [
      { stage: 'Entrevista Técnica', issue: 'Tempo médio elevado (7 dias)', recommendation: 'Aumentar disponibilidade de entrevistadores técnicos' },
    ],
    velocity: 32,
    healthScore: 78,
  },
  outreach: {
    totalSent: 156,
    avgOpenRate: 68,
    avgReplyRate: 38,
    avgInterestRate: 22,
    bestPerformingTemplates: [
      { templateId: 'template-001', name: 'Executive InMail', replyRate: 45 },
      { templateId: 'template-003', name: 'Tech Talent Email', replyRate: 35 },
    ],
    optimalSendTimes: [
      { dayOfWeek: 'Tuesday', hour: 10, performance: 92 },
      { dayOfWeek: 'Wednesday', hour: 14, performance: 88 },
    ],
  },
  aiPerformance: {
    candidatesAnalyzed: 189,
    avgAnalysisAccuracy: 87,
    searchesPerformed: 234,
    avgSearchRelevance: 82,
    outreachGenerated: 89,
    avgOutreachPerformance: 78,
    timeSaved: 48,
    costSavings: 12500,
  },
}
